sudo: required
dist: trusty
language: cpp

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake .. -DMEZZ_BuildDoxygen=OFF

# yes is just an application that returns true, this means perform no installation
install: yes

script: make

after_success: ./Test_Tester

notifications:
  email:
    recipients:
      - contact@blacktoppstudios.com
    on_success: change
    on_failure: always
