sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Debug
      env: CXX_FLAGS=-O0
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Release
      env: CXX_FLAGS=

before_script:
  - mkdir build
  - cd build
  - cmake -E env CXXFLAGS="-fno-var-tracking" cmake -G"Xcode" .. -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_CXX_FLAGS="$CXX_FLAGS" -DMEZZ_BuildDoxygen=OFF -DMEZZ_CodeCoverage=ON

script:
  - cmake --build .
  - ./Test_Tester xml
  - ./Test_Tester skipsummary
  - ./Test_Tester automatic
  - ./Test_Tester Debug All Skip-LoudTests

after_success:
  - cmake --build . TestCoverage
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - contact@blacktoppstudios.com
    on_success: change
    on_failure: always
