sudo: required
dist: bionic
language: cpp

# The `-fno-var-tracking` flag removes some debug information about templates from the build
# that we want most of the time, but can exhaust memory in CI.

matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env: BUILD_TYPE=Debug
      env: CXXFLAGS=-fno-var-tracking
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env: BUILD_TYPE=Release
      env: CXXFLAGS=-fno-var-tracking

before_script:
  - mkdir build
  - cd build
  - cmake -E env CXXFLAGS="-fno-var-tracking" cmake -G"Xcode" .. -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_CXX_FLAGS="$CXX_FLAGS" -DMEZZ_BuildDoxygen=OFF -DMEZZ_CodeCoverage=ON

script:
  - cmake --build .
  - ./Test_Tester xml
  - ./Test_Tester skipsummary
  - ./Test_Tester automatic
  - ./Test_Tester Debug All Skip-LoudTests

after_success:
  - cmake --build . TestCoverage
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - contact@blacktoppstudios.com
    on_success: change
    on_failure: always
